shield/urls.py
from django.contrib import admin
from django.urls import path

import commons.views
import metahumans.views

urlpatterns = [
    path('', commons.views.homepage, name='homepage'),
    path('admin/', admin.site.urls),
    path('metahumans/', metahumans.views.list_all_metahumans, name='metahumans'),
    path('teams/', metahumans.views.list_all_teams, name='teams'), 
    path('teams/<slug>/', metahumans.views.detail_team, name='team_detail'),
    path('amenazas/', metahumans.views.list_dangerous, name='dangerous' )
]

commons/models.py
from django.db import models

# Create your models here.

metahumans/models.py
from django.db import models

# Create your models here.
class Power(models.Model):
    name = models.CharField(max_length=32)
    description = models.CharField(max_length=300)
    level = models.IntegerField(default=50)
    
    def __str__(self):
        return f'{self.name}: {self.description}'

COUNTRIES = [
    ('US', 'United states'),
    ('ES', 'Spain'),
    ('UK', 'United Kingdom'),
    ('OT', "Others"),
    ]



class Team(models.Model):

    class Meta:
        verbose_name = "Equipo"
        verbose_name_plural = "Equipos"

    name = models.CharField(max_length=220)
    description = models.TextField(max_length=4000)
    headquarter =  models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class MetaHuman(models.Model):
    name = models.CharField(max_length=42)
    country = models.CharField(max_length=2, choices=COUNTRIES)
    level = models.IntegerField(default=10)
    active = models.BooleanField(default=True)
    powers = models.ManyToManyField(Power)
    ally = models.BooleanField(default=True)
    last_update = models.DateTimeField(auto_now=True)
    team = models.ForeignKey(
            Team,
            on_delete=models.PROTECT,
            blank=True,
            null=True,
            default=None,
        )
    
    def __str__(self):
        return self.name

commons/views.py
from django.shortcuts import render

# Create your views here.

def homepage(request):
    return render(request, "homepage.html")

metahumans/views.py
from django.shortcuts import render
from .models import MetaHuman, Team
# Create your views here.
def list_all_metahumans(request):
    items = MetaHuman.objects.all()
    return render(request, 'metahumans/list_metahumans.html', {
        'items': items,  # ITEMS ES EL ITERADOR QUE SE VA A USAR EN LIST_METAHUMAN.HTML!!!
    })


def list_all_teams(request):
    items = Team.objects.all()
    return render(request, "metahumans/list_teams.html", {
        "items": items,
    })

def detail_team(request, slug):
    team = Team.objects.get(slug=slug)
    return render(request, "metahumans/detail_team.html", {
        "team": team,
    })

def list_dangerous(request):
    items = MetaHuman.objects.exclude(level__lt=65).exclude(active=False)
    return render(request, "metahumans/list_dangerous.html", {
        'items': items,
    })

commons/templates/base.html
{% load leaflet_tags %}
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %} SHIELD {% endblock title %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    {% leaflet_js %}
    {% leaflet_css %}
  </head>
  <body>
  <section class="section">
    <div class="container">

      <img src="{% static 'logo.png' %}">

      {% include "navbar_bulma.html" %}

        {% block content %}

        {% endblock content %}

    </div>
  </section>
  </body>
</html>

commons/templates/homepage.html
{% extends "base.html" %}
{% load leaflet_tags %} 

{% block js %}{% leaflet_js %}{% endblock %}
{% block css %}{% leaflet_css %}{% endblock %}

{% block title %}SHIELD Homepage{% endblock title %}


{% block content %}

    <h1 class="title">SHIELD</h1>
    <h2 class="subtitle">Strategic Homeland Intervention, Enforcement, and Logistics Division</h2>

    <p>Welcome to our webpage!</p>
    
    {% leaflet_map "globalmap" %}

{% endblock content %}

commons/templates/navbar_bulma.html
{% load static %}
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <img src="{% static 'logo.png' %}" width="28" height="28">
      </a>
  
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
  
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href="{% url 'homepage' %}">
          Inicio
        </a>
  
        <a class="navbar-item" href="{% url 'teams' %}">
          Equipos
        </a>

        <a class="navbar-item" href="{% url 'metahumans' %}">
          Metahumanos
        </a>

        <a class="navbar-item" href="{% url 'dangerous' %}">
          Amenazas
        </a>

        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            More
          </a>
  
          <div class="navbar-dropdown">
            <a class="navbar-item">
              About
            </a>
            <a class="navbar-item">
              Jobs
            </a>
            <a class="navbar-item">
              Contact
            </a>
            <hr class="navbar-divider">
            <a class="navbar-item">
              Report an issue
            </a>
          </div>
        </div>
      </div>
  
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <a class="button is-primary">
              <strong>Sign up</strong>
            </a>
            <a class="button is-light">
              Log in
            </a>
          </div>
        </div>
      </div>
    </div>
  </nav>

metahumans/templates/metahumans/detail_team.html
{% extends 'base.html' %}
{% load shield_filters %}

{% block title %}
    {{ team.name }}
{% endblock title %}

{% block content %}

<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
          {{ team.name }}
      </h1>
      <h2 class="subtitle">
         {{ team.description }} 
      </h2>
      <p><b>Base de operaciones</b>: {{ team.headquarter }}</p>
    </div>
  </div>
</section>

<h2 class="title">
    {{ team.metahuman_set.all.count }}
    Componentes
    </span>
</h2>

<table class="table is-fullwidth is-striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Nivel de amenaza</th>
            <th>Poderes</th>
        </tr>
    </thead>

    {% for mh in team.metahuman_set.all %}
    <tr>
        <td> {{ mh.name }} </td>
        <td> {{ mh.level|danger_level }} </td>
        <td> 
            {% for power in mh.powers.all %}
                {{ power }}
            {% endfor %}
        </td>
    </tr> 
    {% endfor %}
</table>


{% endblock content %}

metahumans/templates/metahumans/list_dangerous.html
{% extends "base.html" %}

{% load shield_filters %}

{% block title %} Listado de metahumanos conocidos {% endblock %}

{% block content %}


<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Equipo</th>
            <th>Poderes</th>
        </tr>
    </thead>

    {% for mh in items %}
    <tr>
        <td> {{ forloop.counter }}:
            
            {{ mh.name }}
            
        </td>
        
        <td>
            {{ mh.team | default:'N/A' }}
        </td>
        <td>
            {% for power in mh.powers.all %}
                {% if not forloop.last %}
                    {{ power.name }},
                {% else %}
                    {{ power.name }}.
                {% endif %}
            {% endfor %}
            
        </td>
    </tr>
    {% endfor %}
</table>

{% endblock content %}

metahumans/templates/metahumans/list_metahumans.html
{% extends "base.html" %}

{% load shield_filters %}

{% block title %} Listado de metahumanos conocidos {% endblock %}

{% block content %}

{% lorem 3 p %}

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Nivel de amenaza</th>
            <th>Equipo</th>
            <th>Poderes</th>
        </tr>
    </thead>

    {% for mh in items %}
    <tr>
        <td> {{ forloop.counter }}.- 
            {% if forloop.first %}
            <strong>{{ mh.name }}</strong> 
            {% else %}
                {{ mh.name }}
            {% endif %}
        </td>
        <td> 
            {{ mh.level | danger_level }} 
        </td>
        <td>
            {{ mh.team | default:'N/A' }}
        </td>
        <td>
            {% for power in mh.powers.all %}
                {% if not forloop.last %}
                    {{ power.name }},
                {% else %}
                    {{ power.name }}.
                {% endif %}
            {% endfor %}
            
        </td>
    </tr>
    {% endfor %}
</table>

{% endblock content %}

metahumans/templates/metahumans/list_teams.html
{% extends "base.html" %}
{% load shield_filters %}

{% block title %} Listado de equipos conocidos {% endblock %}

{% block content %}

<div class='columns is-multiline is-mobile'>

{% for team in items  %}
    <div class='column is-half'>
        <h2 class="title">
            <a href="{% url 'team_detail' slug=team.slug %}">
            {{ team.name }}
       
        </a>
        
        </h2>
        <h3 class='subtitle'>{{ team.description }}</h3>
    </div>
{% endfor %}
</div>
{% endblock content %}